plugins {
    id 'java-library'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'org.openapi.generator' version '7.12.0'
}

group = 'cm.fastrelay'
version = '0.0.1-SNAPSHOT'
description = 'Common classes and methods that need all my projects'

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.boot:spring-boot-dependencies:3.5.7"
    }
}

dependencies {
    // API = exposed to projects that depend on common
    api 'org.springframework.boot:spring-boot-starter-web'
    api 'org.springframework.boot:spring-boot-starter-data-jpa'
    api 'org.springframework.boot:spring-boot-starter-security'
    api 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
    api 'org.springframework.boot:spring-boot-starter-webflux'
    implementation("org.openapitools:openapi-generator:7.12.0")

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.security:spring-security-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}

import org.openapitools.generator.gradle.plugin.tasks.GenerateTask
tasks.register('keycloakOpenApiGenerate', GenerateTask) {
    generatorName = "spring"
    templateDir = "$projectDir/../openapi/templates/spring-http-interface".toString()
    inputSpec = "$projectDir/../openapi/keycloak.yaml".toString()
    outputDir = layout.buildDirectory.dir("generated/sources/openapi").get().asFile.path
    apiPackage = "cm.fastrelay.keycloak.api"
    modelPackage = "cm.fastrelay.keycloak.dto"
    modelNamePrefix = "Keycloak"
    modelNameSuffix = "Dto"
    configOptions = [
            dateLibrary  : "java8-localdatetime",
            library      : "spring-http-interface",
            interfaceOnly: "true",
            useTags      : "true",
    ]
    typeMappings = [
            time: "java.time.LocalTime",
    ]
}

sourceSets {
    main {
        java {
            srcDir layout.buildDirectory.file("generated/sources/openapi/src/main/java").get().asFile.path
        }
    }
}

compileJava.dependsOn(
        tasks.keycloakOpenApiGenerate
)